# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='nextProject',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='public_link_to_project',
        ),
        migrations.AddField(
            model_name='project',
            name='weight',
            field=models.IntegerField(default=1, help_text='This value is used to order ordering assignments. iOS are 100s, android 200s'),
            preserve_default=False,
        ),
    ]
