# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160416_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='course',
        ),
    ]
