# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('projects', '0003_remove_project_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
            preserve_default=False,
        ),
    ]
