# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 22:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20160416_2142'),
        ('projects', '0005_auto_20160416_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField(default=datetime.date.today)),
                ('grade', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('f', 'F')], max_length=7)),
                ('derived_days', models.IntegerField(blank=True, default=0)),
                ('derived_hours', models.FloatField(blank=True, default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Student')),
            ],
        ),
    ]
