# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_studentproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='derived_days',
            field=models.IntegerField(blank=True, default=1, verbose_name='days'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='derived_hours',
            field=models.FloatField(blank=True, default=0, verbose_name='hours'),
        ),
    ]
