# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20160617_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
