# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20160708_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='google_drive_link',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
