# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_google_drive_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproject',
            name='grade',
        ),
        migrations.AlterField(
            model_name='project',
            name='weight',
            field=models.IntegerField(help_text='This value is used to order ordering assignments. iOS - 100s, android 200s'),
        ),
    ]
