# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_full_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='test_after_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
