# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160416_2231'),
        ('course', '0004_remove_course_test_after_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='test_after_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display_test_after', to='projects.Project'),
        ),
    ]
