# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_test_after_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_fee',
            field=models.FloatField(blank=True, default=12000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='test_after_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display_test_after', to='projects.Project'),
        ),
    ]
