# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('note', '0002_auto_20160630_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('type', models.CharField(choices=[('check', 'Check'), ('cash', 'Cash'), ('money order', 'Money Order'), ('credit', 'Credit/Debit Card'), ('deposit', 'EventBrite Deposit'), ('wire', 'Wire transfer'), ('discount', 'Discount'), ('scholarship', 'Scholarship')], max_length=15)),
                ('reference', models.CharField(help_text='A reference number or other information pertanent to this transaction.', max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='note.Note')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTuition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_total', models.FloatField()),
                ('payed_in_full', models.BooleanField(default=False)),
                ('notes', models.ManyToManyField(blank=True, to='note.Note')),
                ('payments', models.ManyToManyField(blank=True, to='finance.Payment')),
            ],
        ),
    ]
