# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='A reference number or other information pertanent to this transaction.', max_length=200),
        ),
        migrations.AlterField(
            model_name='studenttuition',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='tuition', to='finance.Payment'),
        ),
    ]
