# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True, verbose_name='Asset identifier')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_model', models.CharField(choices=[('imac', 'iMac'), ('macbook pro', 'Macbook Pro'), ('macbook_air', 'Macbook Air')], max_length=31)),
                ('year', models.IntegerField(choices=[(2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015)])),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(help_text='e.g. Lion, El Capitan, etc', max_length=31)),
                ('granular_name', models.CharField(help_text='e.g. 10.11.2', max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(help_text='e.g. 7.2.1', max_length=31)),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='computer_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ComputerModel'),
        ),
        migrations.AddField(
            model_name='computer',
            name='operating_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.OperatingSystem'),
        ),
        migrations.AddField(
            model_name='computer',
            name='xcode_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Xcode'),
        ),
    ]
