# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.ComputerModel'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.OperatingSystem'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='xcode_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Xcode'),
        ),
    ]
