# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20160224_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xcode',
            name='version_number',
            field=models.CharField(help_text='e.g. 7.2.1', max_length=31, unique=True),
        ),
    ]
