# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20160224_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='xcode_version',
        ),
    ]
