# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20160416_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computermodel',
            name='computer_model',
            field=models.CharField(choices=[('imac', 'iMac'), ('macbook pro', 'Macbook Pro'), ('macbook_air', 'Macbook Air'), ('imac-ssd', 'iMac (SSD)')], max_length=31),
        ),
    ]
