# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=31)),
                ('last_name', models.CharField(max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('course', models.CharField(choices=[('ios-fulltime', 'iOS full-time intensive'), ('android-fulltime', 'android full-time intensive'), ('swift', 'iOS part-time (Swift)')], default=('ios-fulltime', 'iOS full-time intensive'), max_length=31)),
                ('active', models.BooleanField(default=True)),
                ('computer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_using', to='assets.Computer')),
            ],
        ),
    ]
