# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
