# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('people', '0003_auto_20160222_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
