# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_student_course_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
