# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('people', '0005_remove_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_object',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
            preserve_default=False,
        ),
    ]
