# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160418_1912'),
        ('people', '0007_auto_20160416_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
