# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
        ('people', '0008_student_current_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=63)),
                ('apt', models.CharField(blank=True, max_length=31)),
                ('city', models.CharField(max_length=31)),
                ('state', localflavor.us.models.USStateField()),
                ('zip', localflavor.us.models.USZipCodeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='people.Address')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=63)),
                ('field_of_study', models.CharField(max_length=63)),
                ('degree', models.CharField(choices=[('hs', 'High School'), ('aa', "Associate's Degree"), ('ba', "Bachelor's Degree"), ('ma', "Master's Degree"), ('mba', 'MBA'), ('phd', 'Doctor of Philosophy'), ('other', 'Other')], max_length=7)),
                ('start_date', models.IntegerField(blank=True, choices=[(2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985)])),
                ('end_date', models.IntegerField(blank=True, choices=[(2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985)])),
            ],
        ),
        migrations.CreateModel(
            name='EducationalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_cs_degree', models.BooleanField(default=False)),
                ('incoming_level', models.IntegerField(blank=True, choices=[(0, 'Zero Beginner - no coding knowledge'), (1, 'Beginner - has knowledge of computing concepts, '), (2, 'Starter - some basic knowledge of programming'), (3, 'Mover - knowledge of programming, academic or functional, frameworks'), (4, 'Advanced - CS degree, or equivalent work experience')])),
                ('education', models.ManyToManyField(blank=True, to='people.EducationalExperience')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=31)),
                ('last_name', models.CharField(max_length=31)),
                ('relationship', models.CharField(choices=[('parent', 'Mother/Father'), ('sibling', 'Brother/Sister'), ('relative', 'Other relative'), ('partner', 'Wife/Husband/Spouse'), ('significant-other', 'Girlfriend/Boyfriend/Co-inhabitant'), ('friend', 'Friend/Roommate'), ('other', 'Other')], max_length=31)),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='people.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('website', 'Personal Website'), ('twitter', 'Twitter'), ('other', 'Other')], max_length=15)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TelephoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', localflavor.us.models.PhoneNumberField(blank=True)),
                ('type', models.CharField(blank=True, choices=[('home', 'Home'), ('work', 'Work'), ('iphone', 'iPhone'), ('mobile', 'Mobile'), ('other', 'Other')], max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('first_name',)},
        ),
        migrations.AddField(
            model_name='student',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='work_experience',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.WorkExperience'),
        ),
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='telephone_numbers',
            field=models.ManyToManyField(blank=True, to='people.TelephoneNumber'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone_number',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='people.TelephoneNumber'),
        ),
        migrations.AddField(
            model_name='student',
            name='directory_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.ContactInfo'),
        ),
        migrations.AddField(
            model_name='student',
            name='education',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.EducationalInformation'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.EmergencyContact'),
        ),
        migrations.AddField(
            model_name='student',
            name='links',
            field=models.ManyToManyField(blank=True, to='people.Link'),
        ),
    ]
