# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20160527_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Address'),
        ),
    ]
