# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20160607_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='address',
        ),
    ]
