# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_remove_emergencycontact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='job_search_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
