# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20160630_1156'),
        ('people', '0012_student_job_search_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.ManyToManyField(blank=True, to='note.Note'),
        ),
    ]
