# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20160706_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalinformation',
            name='still_a_student',
            field=models.BooleanField(default=False, verbose_name='Check this if you are still a student.'),
        ),
    ]
