# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_educationalinformation_still_a_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='other_work_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='programming_language_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tech_work_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
