# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20160707_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contract_on_file',
            field=models.BooleanField(default=False),
        ),
    ]
