# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('people', '0018_student_contract_on_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tuition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.StudentTuition'),
        ),
    ]
