# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_student_tuition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tuition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='finance.StudentTuition'),
        ),
    ]
