# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_auto_20160812_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='wants_help_looking_for_a_job',
            field=models.BooleanField(default=False),
        ),
    ]
