# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_student_wants_help_looking_for_a_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='work_experience',
        ),
    ]
