# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_auto_20160906_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='recruit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='recruit.Recruit'),
        ),
    ]
