# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('people', '0025_auto_20160907_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_preferences',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.NotificationPreferences'),
        ),
    ]
