# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.FloatField(blank=True, default=0.0),
            preserve_default=False,
        ),
    ]
