# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_remove_student_work_experience'),
        ('recruit', '0002_job_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('website', models.URLField(blank=True)),
                ('city', models.CharField(blank=True, max_length=31)),
            ],
        ),
        migrations.DeleteModel(
            name='JobSearch',
        ),
        migrations.DeleteModel(
            name='JobSearchSteps',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
