# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20160901_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='recruit.Company'),
            preserve_default=False,
        ),
    ]
