# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20160630_1156'),
        ('recruit', '0004_job_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('website', 'Personal Website'), ('twitter', 'Twitter'), ('other', 'Other')], max_length=15)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wants_help_looking_for_work', models.BooleanField(default=False)),
                ('jobs', models.ManyToManyField(blank=True, to='recruit.Job')),
                ('links', models.ManyToManyField(blank=True, to='recruit.Link')),
                ('notes', models.ManyToManyField(blank=True, to='note.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='resumes')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=31)),
                ('other', models.CharField(blank=True, max_length=63)),
                ('date_to_finish_by', models.DateField()),
            ],
        ),
    ]
