# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_auto_20160907_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Company'),
        ),
    ]
