# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20160630_1156'),
        ('recruit', '0010_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='note.Note'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(choices=[('resume', 'Create resume'), ('github', 'Setup GitHub account and post important projects'), ('website', 'Setup personal portfolio website'), ('linkedin', 'Setup LinkedIn website'), ('side project', 'Finish side project and get in app store.'), ('personal app', 'Create portfolio app'), ('blog', "Create blog with posts about passion for app development, what you're learning, etc"), ('hackathon', 'Participate in Hackathon'), ('other', 'Other Task')], max_length=31),
        ),
    ]
