# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0011_auto_20160908_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='other',
            field=models.CharField(blank=True, max_length=31),
        ),
    ]
