# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0012_link_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('website', 'Personal Website'), ('twitter', 'Twitter'), ('blog', 'Blog'), ('app', 'App Store Link'), ('other', 'Other')], max_length=15),
        ),
    ]
