# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable_all_communication', models.BooleanField(default=False)),
                ('receive_weekly_review', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnsubscribeToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=31)),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
