# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0026_student_email_preferences'),
        ('notifications', '0002_notificationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unsubscribetoken',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='unsubscribetoken',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Student'),
        ),
    ]
