# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_auto_20160222_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('current_project', models.CharField(blank=True, max_length=63)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Student')),
            ],
        ),
    ]
