# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160416_2231'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='current_curriculum_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
