# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_register_current_curriculum_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='forgot_to_checkout',
            field=models.BooleanField(default=False),
        ),
    ]
