# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 20:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_dailyattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 4, 17, 20, 28, 21, 638585, tzinfo=utc)),
        ),
    ]
