# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_dailyattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
