# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20160417_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='date',
            field=models.DateField(),
        ),
    ]
