# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20160417_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='current_project',
        ),
    ]
