# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_student_job_search_status'),
        ('note', '0001_initial'),
        ('attendance', '0010_auto_20160426_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcusedAbsence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, choices=[('sick', 'Sick'), ('vacation', 'Vacation / Traveling'), ('working', 'Working'), ('interviewing', 'Interviewing'), ('other', 'Other')], max_length=31, null=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='note.Note')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Student')),
            ],
        ),
    ]
